class Configuration:
    """ Setting Values """
    INPUT_FILE_NAME = 'input.txt'
    MORNING_SESSION_TIME = 180
    MORNING_SESSION_START_TIME = '9'
    AFTERNOON_SESSION_TIME = 240
    AFTERNOON_SESSION_START_TIME = '13'
    TRACK_TIME = MORNING_SESSION_TIME + AFTERNOON_SESSION_TIME
    LUNCH_TIME = '12'
    MINIMUM_NETWORKING_TIME = '16'
